ip_consumer_auth.settings:
  type: config_object
  label: 'IP Consumer Auth settings'
  mapping:
    ip_consumers:
      type: string
      label: 'IP addresses'
    list_type:
      type: integer
      label: 'Type of IP list'
    format:
      type: sequence
      label: 'Allowed formats'
      sequence:
        type: string
        label: 'Allowed format'
